Repository Run-Us/Run-Us-server, pull requests merged in 2024-11, with the labels that each got.

#44 [Feature/shift-aggregate-api-to-post] - 결과저장요청 POST로 변경
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/controller/model/RunningHttpResponseCode.java
  src/main/java/com/run_us/server/domains/running/controller/model/request/MultiRunRecordRequest.java
  src/main/java/com/run_us/server/domains/running/controller/model/request/RunningRequest.java
  src/main/java/com/run_us/server/domains/running/controller/model/request/SingleRunRecordRequest.java
  src/main/java/com/run_us/server/domains/running/domain/running/Running.java
  src/main/java/com/run_us/server/domains/running/domain/running/RunningConstraints.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/domains/running/service/model/RunningAggregation.java
  src/main/java/com/run_us/server/domains/running/service/model/RunningAggregations.java
  src/main/java/com/run_us/server/domains/running/service/model/RunningMapper.java
  src/main/java/com/run_us/server/global/security/JwtAuthenticationFilter.java
  src/test/java/com/run_us/server/domains/running/RunningFixtures.java
  src/test/java/com/run_us/server/domains/running/RunningTest.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :rotating_light: L3

#45 [Feat/user-auth] 회원가입 및 로그인
  src/main/java/com/run_us/server/domains/user/controller/AuthController.java
  src/main/java/com/run_us/server/domains/user/controller/TestAuthController.java
  src/main/java/com/run_us/server/domains/user/controller/UserController.java
  src/main/java/com/run_us/server/domains/user/controller/model/request/AuthLoginRequest.java
  src/main/java/com/run_us/server/domains/user/controller/model/request/AuthSignupRequest.java
  src/main/java/com/run_us/server/domains/user/controller/model/request/UserSignUpRequest.java
  src/main/java/com/run_us/server/domains/user/controller/model/response/AuthResponse.java
  src/main/java/com/run_us/server/domains/user/domain/Profile.java
  src/main/java/com/run_us/server/domains/user/repository/OAuthInfoRepository.java
  src/main/java/com/run_us/server/domains/user/repository/OAuthRedisRepository.java
  src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
  src/main/java/com/run_us/server/domains/user/service/JwtService.java
  src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
  src/main/java/com/run_us/server/domains/user/service/verifier/KakaoTokenVerifier.java
  src/main/java/com/run_us/server/domains/user/service/verifier/TokenVerifier.java
  src/main/java/com/run_us/server/global/config/SecurityConfig.java
  src/main/java/com/run_us/server/global/validator/EnumValidator.java
  src/main/java/com/run_us/server/global/validator/annotation/EnumValid.java
  src/main/resources/application.yml
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#49 [Environment] - 개발환경에서 더미데이터 생성
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: :hammer_and_pick: enhancement :hammer_and_pick:

#47 Feat/increase user total distance
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/controller/model/response/RunningCreateResponse.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/domains/user/domain/Profile.java
  src/main/java/com/run_us/server/domains/user/domain/User.java
  src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
  src/test/java/com/run_us/server/domains/user/domain/PenaltyRepositoryTest.java
  src/test/java/com/run_us/server/domains/user/domain/UserRepositoryTest.java
  src/test/java/com/run_us/server/domains/user/domain/UserTest.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :face_with_diagonal_mouth: L2

#53 [Feat/auth-enhancement] - 인메모리 캐시 클래스 추가 및 OIDC 검증 로직 개선
  src/main/java/com/run_us/server/domains/user/domain/OAuthToken.java
  src/main/java/com/run_us/server/domains/user/domain/TokenStatus.java
  src/main/java/com/run_us/server/domains/user/repository/OAuthRedisRepository.java
  src/main/java/com/run_us/server/domains/user/repository/OAuthTokenRepository.java
  src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
  src/main/java/com/run_us/server/domains/user/service/verifier/KakaoTokenVerifier.java
  src/main/java/com/run_us/server/global/common/cache/CacheEntry.java
  src/main/java/com/run_us/server/global/common/cache/InMemoryCache.java
  src/main/java/com/run_us/server/global/common/cache/SpringInMemoryCache.java
  src/main/java/com/run_us/server/global/config/CacheConfig.java
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#55 [Fix login/signup response, add auth exception handling logic] - 로그인, 회원가입 응답 수정, 에러 핸들링
  src/main/java/com/run_us/server/domains/user/controller/AuthController.java
  src/main/java/com/run_us/server/domains/user/controller/model/response/AuthResponse.java
  src/main/java/com/run_us/server/domains/user/controller/model/response/UserHttpResponseCode.java
  src/main/java/com/run_us/server/domains/user/exception/UserAuthException.java
  src/main/java/com/run_us/server/domains/user/exception/UserErrorCode.java
  src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
  src/main/java/com/run_us/server/global/exception/GlobalExceptionHandler.java
Labels: :bug: bug :bug:, :rotating_light: L3

#54 [Feat/update running domain] - 러닝 도메인 재작성
  src/main/java/com/run_us/server/domains/running/exception/RunningErrorCode.java
  src/main/java/com/run_us/server/v2/RunningException.java
  src/main/java/com/run_us/server/v2/RunningHttpResponseCode.java
  src/main/java/com/run_us/server/v2/running/run/controller/RunController.java
  src/main/java/com/run_us/server/v2/running/run/controller/RunPreviewController.java
  src/main/java/com/run_us/server/v2/running/run/controller/model/request/SessionRunCreateRequest.java
  src/main/java/com/run_us/server/v2/running/run/domain/Participant.java
  src/main/java/com/run_us/server/v2/running/run/domain/Run.java
  src/main/java/com/run_us/server/v2/running/run/domain/RunPace.java
  src/main/java/com/run_us/server/v2/running/run/domain/RunStatus.java
  src/main/java/com/run_us/server/v2/running/run/domain/RunningPreview.java
  src/main/java/com/run_us/server/v2/running/run/repository/ParticipantRepository.java
  src/main/java/com/run_us/server/v2/running/run/repository/RunRepository.java
  src/main/java/com/run_us/server/v2/running/run/service/DateUtils.java
  src/main/java/com/run_us/server/v2/running/run/service/ParticipantService.java
  src/main/java/com/run_us/server/v2/running/run/service/RunCommandService.java
  src/main/java/com/run_us/server/v2/running/run/service/RunQueryService.java
  src/main/java/com/run_us/server/v2/running/run/service/RunValidator.java
  src/main/java/com/run_us/server/v2/running/run/service/model/GetRunPreviewResponse.java
  src/main/java/com/run_us/server/v2/running/run/service/model/ParticipantInfo.java
  src/main/java/com/run_us/server/v2/running/run/service/model/RunCreateResponse.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCase.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCaseImpl.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunPreviewUseCase.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunPreviewUseCaseImpl.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunRegisterUseCase.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunRegisterUseCaseImpl.java
  src/test/java/com/run_us/server/v2/RunFixtures.java
  src/test/java/com/run_us/server/v2/RunTest.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :rotating_light: L3, :recycle: refactoring :recycle:

#57 [Feat/implement passcode generator for live runningSession] - 입장코드 발급 기능 개발
  src/main/java/com/run_us/server/v2/RunningHttpResponseCode.java
  src/main/java/com/run_us/server/v2/running/common/PassCodeGenerator.java
  src/main/java/com/run_us/server/v2/running/common/PassCodeRegistry.java
  src/main/java/com/run_us/server/v2/running/common/RedisPassCodeRegistry.java
  src/main/java/com/run_us/server/v2/running/run/controller/RunController.java
  src/main/java/com/run_us/server/v2/running/run/domain/Run.java
  src/main/java/com/run_us/server/v2/running/run/service/model/CustomRunCreateResponse.java
  src/main/java/com/run_us/server/v2/running/run/service/model/SessionRunCreateResponse.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCase.java
  src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCaseImpl.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :face_with_diagonal_mouth: L2
