Repository Run-Us/Run-Us-server, pull requests merged in 2024-10, with the labels that each got.

#26 [Feature/validate subscribe] - 채널 구독시 검증로직 추가
  src/main/java/com/run_us/server/domains/running/controller/StompInterceptor.java
  src/main/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopic.java
  src/main/java/com/run_us/server/domains/running/service/SubscriptionService.java
  src/main/java/com/run_us/server/global/common/GlobalConsts.java
  src/test/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopicTest.java
Labels: :bug: bug :bug:, :hammer_and_pick: enhancement :hammer_and_pick:

#29 [Fix/send to user] - 특정유저에게 전송하기 수정
  src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopic.java
  src/main/java/com/run_us/server/domains/running/exceptions/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/service/SubscriptionService.java
Labels: :bug: bug :bug:, :face_with_diagonal_mouth: L2

#31 [Refactor/after prototype] 프로토타입 구현 후 정리 리팩토링
  src/main/java/com/run_us/server/domains/running/RunningConst.java
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/controller/StompInterceptor.java
  src/main/java/com/run_us/server/domains/running/controller/model/RunningSocketResponseCode.java
  src/main/java/com/run_us/server/domains/running/controller/model/SubscriptionTopic.java
  src/main/java/com/run_us/server/domains/running/controller/model/enums/RunningResponseCode.java
  src/main/java/com/run_us/server/domains/running/domain/Running.java
  src/main/java/com/run_us/server/domains/running/domain/RunningConst.java
  src/main/java/com/run_us/server/domains/running/domain/RunningConstraints.java
  src/main/java/com/run_us/server/domains/running/domain/RunningDescription.java
  src/main/java/com/run_us/server/domains/running/exception/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/exception/RunningException.java
  src/main/java/com/run_us/server/domains/running/exception/RunningNotFoundException.java
  src/main/java/com/run_us/server/domains/running/repository/RunningRedisRepository.java
  src/main/java/com/run_us/server/domains/running/service/RunningLiveService.java
  src/main/java/com/run_us/server/domains/running/service/RunningPreparationService.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/domains/running/service/SubscriptionService.java
  src/main/java/com/run_us/server/domains/running/service/model/JoinedParticipant.java
  src/main/java/com/run_us/server/domains/running/service/util/RunningKeyUtil.java
  src/main/java/com/run_us/server/domains/test/TestController.java
  src/main/java/com/run_us/server/domains/user/domain/Penalty.java
  src/main/java/com/run_us/server/domains/user/exception/UserErrorCode.java
  src/main/java/com/run_us/server/domains/user/exception/UserException.java
  src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
  src/main/java/com/run_us/server/domains/user/service/UserService.java
  src/main/java/com/run_us/server/global/common/DateAudit.java
  src/main/java/com/run_us/server/global/common/ErrorResponse.java
  src/main/java/com/run_us/server/global/common/GlobalConst.java
  src/main/java/com/run_us/server/global/common/Response.java
  src/main/java/com/run_us/server/global/common/SocketConst.java
  src/main/java/com/run_us/server/global/common/SuccessResponse.java
  src/main/java/com/run_us/server/global/config/SecurityConfig.java
  src/main/java/com/run_us/server/global/config/WebSocketConfig.java
  src/main/java/com/run_us/server/global/exception/BusinessException.java
  src/main/java/com/run_us/server/global/exception/ExampleException.java
  src/main/java/com/run_us/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
  src/main/java/com/run_us/server/global/exception/code/CustomResponseCode.java
  src/main/java/com/run_us/server/global/exception/code/ExampleErrorCode.java
  src/main/java/com/run_us/server/global/util/JsonConverter.java
  src/main/java/com/run_us/server/global/util/P6SpyFormatter.java
  src/main/java/com/run_us/server/global/util/PassCodeGenerator.java
  src/main/java/com/run_us/server/global/util/PointGenerator.java
  src/test/java/com/run_us/server/domains/running/RunningControllerTest.java
  src/test/java/com/run_us/server/domains/running/RunningFixtures.java
  src/test/java/com/run_us/server/domains/running/RunningTest.java
  src/test/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopicTest.java
  src/test/java/com/run_us/server/domains/running/repository/InMemoryLocationLogsTest.java
  src/test/java/com/run_us/server/domains/user/domain/PenaltyRepositoryTest.java
Labels: :smile: L1, :recycle: refactoring :recycle:

#33 [Feature/save running record] - 개인 기록 저장 및 조회 개발
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/controller/model/request/RunningCreateRequest.java
  src/main/java/com/run_us/server/domains/running/controller/model/request/RunningRequest.java
  src/main/java/com/run_us/server/domains/running/controller/model/response/RunningCreateResponse.java
  src/main/java/com/run_us/server/domains/running/domain/LocationData.java
  src/main/java/com/run_us/server/domains/running/domain/RunningType.java
  src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
  src/main/java/com/run_us/server/domains/running/domain/record/RunningRecord.java
  src/main/java/com/run_us/server/domains/running/domain/record/RunningType.java
  src/main/java/com/run_us/server/domains/running/domain/running/ParticipantStatus.java
  src/main/java/com/run_us/server/domains/running/domain/running/Participants.java
  src/main/java/com/run_us/server/domains/running/domain/running/Running.java
  src/main/java/com/run_us/server/domains/running/domain/running/RunningConstraints.java
  src/main/java/com/run_us/server/domains/running/domain/running/RunningDescription.java
  src/main/java/com/run_us/server/domains/running/exception/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/repository/PersonalRecordRepository.java
  src/main/java/com/run_us/server/domains/running/repository/RunningRedisRepository.java
  src/main/java/com/run_us/server/domains/running/repository/RunningRepository.java
  src/main/java/com/run_us/server/domains/running/service/RunningLiveService.java
  src/main/java/com/run_us/server/domains/running/service/RunningPreparationService.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/domains/running/service/model/PersonalRecordQueryResult.java
  src/main/java/com/run_us/server/domains/running/service/model/RunningAggregation.java
  src/main/java/com/run_us/server/domains/running/service/model/RunningMapper.java
  src/test/java/com/run_us/server/domains/running/PersonalRecordFixtures.java
  src/test/java/com/run_us/server/domains/running/RunningControllerTest.java
  src/test/java/com/run_us/server/domains/running/RunningFixtures.java
  src/test/java/com/run_us/server/domains/running/RunningRedisRepositoryTest.java
  src/test/java/com/run_us/server/domains/running/RunningTest.java
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#34 [Feat/socket handler] 소켓 에러 핸들리 - 기존 핸들러 수정, Controller 단 핸들러 추가 구현
  src/main/java/com/run_us/server/domains/test/TestController.java
  src/main/java/com/run_us/server/global/common/SocketConst.java
  src/main/java/com/run_us/server/global/exception/GlobalSocketExceptionHandler.java
  src/main/java/com/run_us/server/global/exception/SocketBusinessExceptionHandler.java
  src/main/java/com/run_us/server/global/exception/SocketExceptionCustomHandler.java
  src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :smile: L1

#36 [FIX/application-env] - 환경세팅 긴급 수정
  src/main/java/com/run_us/server/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: :bug: bug :bug:, :rotating_light: L3

#38 [Refactor/get user] 소켓 통신 시 유저정보 가져오는 로직 변경 +작은 리팩토링들, 로깅 룰 제안
  src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/controller/model/UserSocketResponseCode.java
  src/main/java/com/run_us/server/domains/running/domain/running/Running.java
  src/main/java/com/run_us/server/domains/running/service/RunningLiveService.java
  src/main/java/com/run_us/server/domains/running/service/RunningPreparationService.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/domains/running/service/SubscriptionService.java
  src/main/java/com/run_us/server/global/common/SocketConst.java
  src/main/java/com/run_us/server/global/config/StompInterceptor.java
  src/main/java/com/run_us/server/global/config/WebSocketConfig.java
  src/main/java/com/run_us/server/global/exception/SocketBusinessExceptionInterceptor.java
  src/main/java/com/run_us/server/global/exception/SocketExceptionCustomInterceptor.java
  src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
  src/main/java/com/run_us/server/global/exception/UserSocketException.java
Labels: :smile: L1, :recycle: refactoring :recycle:

#37 [Refactor/erd-sync] ERD에 맞게 타입 싱크
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
  src/main/java/com/run_us/server/domains/running/domain/record/RunningRecord.java
  src/main/java/com/run_us/server/domains/running/domain/running/Participants.java
  src/main/java/com/run_us/server/domains/running/domain/running/Running.java
  src/main/java/com/run_us/server/domains/running/repository/PersonalRecordRepository.java
  src/main/java/com/run_us/server/domains/running/service/RunningPreparationService.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/domains/running/service/model/RunningMapper.java
  src/main/java/com/run_us/server/domains/user/controller/UserController.java
  src/main/java/com/run_us/server/domains/user/domain/OAuthInfo.java
  src/main/java/com/run_us/server/domains/user/domain/Penalty.java
  src/main/java/com/run_us/server/domains/user/domain/Profile.java
  src/main/java/com/run_us/server/domains/user/domain/User.java
  src/main/java/com/run_us/server/domains/user/repository/PenaltyRepository.java
  src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
  src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
  src/main/java/com/run_us/server/global/common/CreationTimeAudit.java
  src/main/java/com/run_us/server/global/common/DateAudit.java
  src/main/java/com/run_us/server/global/common/SuccessResponse.java
  src/test/java/com/run_us/server/domains/running/PersonalRecordFixtures.java
  src/test/java/com/run_us/server/domains/running/RunningControllerTest.java
  src/test/java/com/run_us/server/domains/running/RunningTest.java
  src/test/java/com/run_us/server/domains/user/domain/PenaltyRepositoryTest.java
  src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
  src/test/java/com/run_us/server/domains/user/domain/UserRepositoryTest.java
  src/test/java/com/run_us/server/domains/user/domain/UserTest.java
Labels: :smile: L1, :recycle: refactoring :recycle:

#39 [Refactor/remove-examplecode-usage] - Remove ExampleErrorCode Usage
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/controller/model/RunningHttpResponseCode.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :face_with_diagonal_mouth: L2

#41 [Refactor/running-dto-and-controller] - refactor running controller
  src/main/java/com/run_us/server/domains/running/controller/RunningController.java
  src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/controller/aop/UserId.java
  src/main/java/com/run_us/server/domains/running/controller/aop/UserIdArgumentResolver.java
  src/main/java/com/run_us/server/domains/running/controller/model/request/RunningRequest.java
  src/main/java/com/run_us/server/domains/running/controller/model/response/RunningResponse.java
  src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
  src/main/java/com/run_us/server/global/config/WebSocketConfig.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :face_with_diagonal_mouth: L2, :recycle: refactoring :recycle:
