Repository Run-Us/Run-Us-server, pull requests merged in 2024-09, with the labels that each got.

#4 Feature/user entity
  build.gradle
  src/main/java/com/run_us/server/domain/user/model/Gender.java
  src/main/java/com/run_us/server/domain/user/model/OAuthInfo.java
  src/main/java/com/run_us/server/domain/user/model/Penalty.java
  src/main/java/com/run_us/server/domain/user/model/SocialProvider.java
  src/main/java/com/run_us/server/domain/user/model/User.java
  src/main/java/com/run_us/server/domain/user/repository/OAuthInfoRepository.java
  src/main/java/com/run_us/server/domain/user/repository/PenaltyRepository.java
  src/main/java/com/run_us/server/domain/user/repository/UserRepository.java
  src/main/java/com/run_us/server/global/common/DateAudit.java
  src/main/java/com/run_us/server/global/common/GlobalConsts.java
  src/test/java/com/run_us/server/domain/user/model/PenaltyRepositoryTest.java
  src/test/java/com/run_us/server/domain/user/model/UserRepositoryTest.java
  src/test/java/com/run_us/server/domain/user/model/UserTest.java
Labels: enhancement

#8 [Bug] user entity builder
  src/main/java/com/run_us/server/domain/user/model/User.java
  src/test/java/com/run_us/server/domain/user/model/PenaltyRepositoryTest.java
  src/test/java/com/run_us/server/domain/user/model/UserFixtures.java
  src/test/java/com/run_us/server/domain/user/model/UserRepositoryTest.java
  src/test/java/com/run_us/server/domain/user/model/UserTest.java
Labels: bug

#10 Feature/running session management
  build.gradle
  src/main/java/com/run_us/server/domain/running/model/LocationData.java
  src/main/java/com/run_us/server/domain/running/model/ParticipantStatus.java
  src/main/java/com/run_us/server/domain/running/model/RunningConstants.java
  src/main/java/com/run_us/server/domain/running/repository/RunningRedisRepository.java
  src/main/java/com/run_us/server/domain/running/service/RunningService.java
  src/main/java/com/run_us/server/global/config/RedisConfig.java
Labels: enhancement

#13 [Feature/add embedded redis] 테스트환경을 위한 Embedded Redis 설정
  .github/workflows/develop-ci.yml
  build.gradle
  src/main/java/com/run_us/server/global/config/RedisConfig.java
  src/test/java/com/run_us/server/config/EmbeddedRedisConfiguration.java
  src/test/java/com/run_us/server/config/TestRedisConfiguration.java
  src/test/java/com/run_us/server/domain/running/RunningRedisRepositoryTest.java
Labels: enhancement, test

#17 [Feat/ws auth] STOMP CONNECT 시 User 정보 세션저장, StompErrorHandler 구현
  src/main/java/com/run_us/server/domains/running/controller/StompInterceptor.java
  src/main/java/com/run_us/server/domains/test/TestController.java
  src/main/java/com/run_us/server/domains/user/model/response/UserErrorCode.java
  src/main/java/com/run_us/server/domains/user/model/response/UserException.java
  src/main/java/com/run_us/server/domains/user/service/UserService.java
  src/main/java/com/run_us/server/global/common/GlobalConsts.java
  src/main/java/com/run_us/server/global/config/WebSocketConfig.java
  src/main/java/com/run_us/server/global/exceptions/StompErrorHandler.java
Labels: enhancement

#19 [Feature/save location update log] - 유저의 실시간 위치 업데이트 저장기능
  src/main/java/com/run_us/server/domains/running/repository/InMemoryLocationLogs.java
  src/main/java/com/run_us/server/domains/running/repository/RunningRedisRepository.java
  src/main/java/com/run_us/server/domains/running/repository/UpdateLocationRepository.java
  src/main/java/com/run_us/server/domains/running/service/RunningLiveService.java
  src/main/java/com/run_us/server/domains/running/service/utils/RunningServiceUtils.java
  src/test/java/com/run_us/server/domains/running/repository/InMemoryLocationLogsTest.java
Labels: enhancement

#22 [Feat/ws auth] 자잘한 수정 + SendToUser 저도 안됨 소식
  src/main/java/com/run_us/server/domains/running/exceptions/RunningNotFoundException.java
  src/main/java/com/run_us/server/domains/test/TestController.java
  src/main/java/com/run_us/server/domains/user/model/User.java
  src/main/java/com/run_us/server/domains/user/model/response/UserErrorCode.java
  src/main/java/com/run_us/server/domains/user/service/UserService.java
  src/main/java/com/run_us/server/global/common/GlobalConsts.java
  src/main/java/com/run_us/server/global/config/WebSocketConfig.java
Labels: bug, enhancement, help wanted
