Repository Run-Us/Run-Us-server, pull requests merged in 2024-12, with the labels that each got.

#62 [create crew] crew 도메인 구성
  src/main/java/com/run_us/server/domains/crew/controller/model/response/CrewHttpResponseCode.java
  src/main/java/com/run_us/server/domains/crew/domain/Crew.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewDescription.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewMembership.java
  src/main/java/com/run_us/server/domains/crew/domain/enums/CrewJoinRequestStatus.java
  src/main/java/com/run_us/server/domains/crew/domain/enums/CrewJoinType.java
  src/main/java/com/run_us/server/domains/crew/domain/enums/CrewMembershipRole.java
  src/main/java/com/run_us/server/domains/crew/domain/enums/CrewStatus.java
  src/main/java/com/run_us/server/domains/crew/domain/enums/CrewThemeType.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :smile: L1

#63 [Feat/crew join request process] - 크루 가입요청 생성 및 취소
  src/main/java/com/run_us/server/domains/crew/controller/CrewController.java
  src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewErrorCode.java
  src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewException.java
  src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewHttpResponseCode.java
  src/main/java/com/run_us/server/domains/crew/controller/model/request/CreateJoinRequest.java
  src/main/java/com/run_us/server/domains/crew/controller/model/response/CancelJoinRequestResponse.java
  src/main/java/com/run_us/server/domains/crew/controller/model/response/CreateJoinRequestResponse.java
  src/main/java/com/run_us/server/domains/crew/controller/model/response/CrewJoinRequestInternalResponse.java
  src/main/java/com/run_us/server/domains/crew/domain/Crew.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
  src/main/java/com/run_us/server/domains/crew/domain/enums/CrewJoinRequestStatus.java
  src/main/java/com/run_us/server/domains/crew/repository/CrewRepository.java
  src/main/java/com/run_us/server/domains/crew/service/CrewService.java
  src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
  src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCase.java
  src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCaseImpl.java
  src/main/java/com/run_us/server/domains/user/exception/UserException.java
  src/main/java/com/run_us/server/global/config/CacheConfig.java
  src/main/java/com/run_us/server/global/config/WebMvcConfig.java
  src/main/java/com/run_us/server/global/security/annotation/CurrentUser.java
  src/main/java/com/run_us/server/global/security/principal/UserPrincipal.java
  src/main/java/com/run_us/server/global/security/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/run_us/server/global/security/resolver/UserIdResolver.java
Labels: question, :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#64 [Feat/create-running-session] - 세션런 생성 API 개발
  src/main/java/com/run_us/server/domains/running/common/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/run/controller/RunPreviewController.java
  src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionAccessLevel.java
  src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionRunCreateRequest.java
  src/main/java/com/run_us/server/domains/running/run/domain/RunningPreview.java
  src/main/java/com/run_us/server/domains/running/run/repository/ParticipantRepository.java
  src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
  src/main/java/com/run_us/server/domains/running/run/service/ParticipantService.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCase.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCaseImpl.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunRegisterUseCaseImpl.java
  src/test/java/com/run_us/server/domains/running/RunFixtures.java
  src/test/java/com/run_us/server/domains/running/RunTest.java
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#66 [Feat/delete-running-session] - 러닝세션 삭제 API 개발
  src/main/java/com/run_us/server/domains/running/common/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/run/controller/RunController.java
  src/main/java/com/run_us/server/domains/running/run/domain/Run.java
  src/main/java/com/run_us/server/domains/running/run/domain/RunStatus.java
  src/main/java/com/run_us/server/domains/running/run/service/RunCommandService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunValidator.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCaseImpl.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunDeleteUseCase.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunDeleteUseCaseImpl.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunPreviewUseCaseImpl.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunRegisterUseCaseImpl.java
  src/test/java/com/run_us/server/domains/running/ParticipantFixtures.java
  src/test/java/com/run_us/server/domains/running/RunRepositoryTest.java
  src/test/java/com/run_us/server/domains/running/RunTest.java
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#67 [Feat/crew join request review] - 크루 가입요청 조회 및 승인/거절 처리
  src/main/java/com/run_us/server/domains/crew/controller/CrewController.java
  src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewErrorCode.java
  src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewHttpResponseCode.java
  src/main/java/com/run_us/server/domains/crew/controller/model/request/ReviewJoinRequest.java
  src/main/java/com/run_us/server/domains/crew/controller/model/response/FetchJoinRequestResponse.java
  src/main/java/com/run_us/server/domains/crew/controller/model/response/ReviewJoinRequestResponse.java
  src/main/java/com/run_us/server/domains/crew/domain/Crew.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
  src/main/java/com/run_us/server/domains/crew/repository/CrewRepository.java
  src/main/java/com/run_us/server/domains/crew/service/CrewService.java
  src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
  src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCase.java
  src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCaseImpl.java
  src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
  src/main/java/com/run_us/server/domains/user/service/UserService.java
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#68 [Feat/register-running-session] - 러닝세션 참가 API 개발
  src/main/java/com/run_us/server/domains/running/common/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/run/controller/RunController.java
  src/main/java/com/run_us/server/domains/running/run/controller/model/RunningHttpResponseCode.java
  src/main/java/com/run_us/server/domains/running/run/domain/Run.java
  src/main/java/com/run_us/server/domains/running/run/domain/RunStatus.java
  src/main/java/com/run_us/server/domains/running/run/service/ParticipantService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunValidator.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunRegisterUseCase.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunRegisterUseCaseImpl.java
Labels: :rocket: feature :rocket:
