Repository Run-Us/Run-Us-server, pull requests merged in 2025-01, with the labels that each got.

#69 [Feat/fetch-joined-running] - 참가한 러닝 조회
  src/main/java/com/run_us/server/domains/running/run/controller/RunController.java
  src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionRunCreateRequest.java
  src/main/java/com/run_us/server/domains/running/run/domain/Run.java
  src/main/java/com/run_us/server/domains/running/run/domain/RunningPreview.java
  src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
  src/main/java/com/run_us/server/domains/running/run/service/RunCommandService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
  src/main/java/com/run_us/server/domains/running/run/service/model/HostInfo.java
  src/main/java/com/run_us/server/domains/running/run/service/model/JoinedRunPreviewResponse.java
  src/main/java/com/run_us/server/domains/running/run/service/model/RunCreateDto.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCase.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCaseImpl.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunPreviewUseCase.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunPreviewUseCaseImpl.java
  src/test/java/com/run_us/server/domains/running/RunFixtures.java
  src/test/java/com/run_us/server/domains/running/RunRepositoryTest.java
  src/test/java/com/run_us/server/domains/running/RunTest.java
Labels: :rocket: feature :rocket:, :face_with_diagonal_mouth: L2

#70 [Feat/create-crew-session-run] - 크루용 러닝세션 생성 적용
  src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionAccessLevel.java
  src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionRunCreateRequest.java
  src/main/java/com/run_us/server/domains/running/run/domain/Run.java
  src/main/java/com/run_us/server/domains/running/run/domain/RunningPreview.java
  src/main/java/com/run_us/server/domains/running/run/domain/SessionAccessLevel.java
  src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
  src/main/java/com/run_us/server/domains/running/run/service/RunCommandService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunValidator.java
  src/main/java/com/run_us/server/domains/running/run/service/model/RunCreateDto.java
  src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCaseImpl.java
  src/test/java/com/run_us/server/domains/running/RunFixtures.java
  src/test/java/com/run_us/server/domains/running/RunRepositoryTest.java
  src/test/java/com/run_us/server/domains/running/RunTest.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :rocket: feature :rocket:

#72 [Fix/Run-with-crew] - 크루, 접근제한 버그 수정
  src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
  src/test/java/com/run_us/server/domains/running/RunTest.java
Labels: :bug: bug :bug:

#74 [Fix/fetch-pace-categories] - 페이스 N개를 한번에 조회할때 에러 발생
  src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
  src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
  src/main/java/com/run_us/server/domains/running/run/service/model/GetRunPreviewResponse.java
Labels: :bug: bug :bug:

#71 [Fix/crew-domain] - CrewJoinRequest 수정
  src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewErrorCode.java
  src/main/java/com/run_us/server/domains/crew/domain/Crew.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
  src/main/java/com/run_us/server/domains/crew/domain/CrewMembership.java
  src/main/java/com/run_us/server/domains/crew/repository/CrewJoinRequestRepository.java
  src/main/java/com/run_us/server/domains/crew/repository/CrewRepository.java
  src/main/java/com/run_us/server/domains/crew/service/CrewService.java
  src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
  src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCaseImpl.java
  src/test/java/com/run_us/server/domains/crew/domain/CrewFixtures.java
  src/test/java/com/run_us/server/domains/crew/domain/CrewJoinRequestRepositoryTest.java
  src/test/java/com/run_us/server/domains/crew/service/CrewValidatorTest.java
Labels: :bug: bug :bug:, :rotating_light: L3

#77 [Run/open-live-session] - 실시간 대기방 생성 API 개발
  src/main/java/com/run_us/server/domains/running/common/RedisPassCodeRegistry.java
  src/main/java/com/run_us/server/domains/running/common/RunningConst.java
  src/main/java/com/run_us/server/domains/running/common/RunningErrorCode.java
  src/main/java/com/run_us/server/domains/running/live/controller/LiveRunningController.java
  src/main/java/com/run_us/server/domains/running/live/controller/RunningSocketController.java
  src/main/java/com/run_us/server/domains/running/live/controller/model/SubscriptionTopic.java
  src/main/java/com/run_us/server/domains/running/live/repository/RunningRedisRepository.java
  src/main/java/com/run_us/server/domains/running/live/service/RunningLiveService.java
  src/main/java/com/run_us/server/domains/running/live/service/model/LiveRunningCreateResponse.java
  src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCase.java
  src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCaseImpl.java
  src/main/java/com/run_us/server/domains/running/live/service/util/RunningKeyUtil.java
  src/main/java/com/run_us/server/domains/running/run/domain/Run.java
  src/main/java/com/run_us/server/domains/running/run/repository/ParticipantRepository.java
  src/main/java/com/run_us/server/domains/running/run/service/ParticipantService.java
  src/main/java/com/run_us/server/domains/running/run/service/RunValidator.java
  src/test/java/com/run_us/server/domains/crew/domain/CrewJoinRequestRepositoryTest.java
  src/test/java/com/run_us/server/domains/crew/service/CrewValidatorTest.java
  src/test/java/com/run_us/server/domains/running/RunTest.java
  src/test/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopicTest.java
Labels: :rocket: feature :rocket:

#80 [HOTFIX : fix currentUser ripple effect] - run live controller 핫픽스
  src/main/java/com/run_us/server/domains/running/live/controller/LiveRunningController.java
  src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCase.java
  src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCaseImpl.java
  src/main/java/com/run_us/server/global/config/CacheConfig.java
Labels: :bug: bug :bug:, :rotating_light: L3, :recycle: refactoring :recycle:

#81 [Feat/auth refresh] - 토큰 리프레시 로직 구현
  src/main/java/com/run_us/server/domains/user/controller/AuthController.java
  src/main/java/com/run_us/server/domains/user/controller/model/request/AuthRefreshRequest.java
  src/main/java/com/run_us/server/domains/user/controller/model/response/UserHttpResponseCode.java
  src/main/java/com/run_us/server/domains/user/domain/AuthResultType.java
  src/main/java/com/run_us/server/domains/user/exception/UserErrorCode.java
  src/main/java/com/run_us/server/domains/user/service/JwtService.java
  src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
  src/main/java/com/run_us/server/global/common/cache/InMemoryCache.java
  src/main/java/com/run_us/server/global/common/cache/RedisInMemoryCache.java
  src/main/java/com/run_us/server/global/common/cache/SpringInMemoryCache.java
  src/main/java/com/run_us/server/global/config/CacheConfig.java
  src/main/java/com/run_us/server/global/config/RedisConfig.java
Labels: :hammer_and_pick: enhancement :hammer_and_pick:, :rocket: feature :rocket:, :smile: L1
